package page.loanoriginationsystem;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ApplicantEmployerDetails implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Employer Type")
   private java.lang.String applicantEmployerType;
   @org.kie.api.definition.type.Label(value = "Employer Name")
   private java.lang.String applicantEmployerName;
   @org.kie.api.definition.type.Label(value = "Employer Name Others")
   private java.lang.String applicantEmployerNameOthers;
   @org.kie.api.definition.type.Label(value = "Employer Address")
   private java.lang.String applicantEmployerAddress;
   @org.kie.api.definition.type.Label(value = "Nearest Land Mark")
   private java.lang.String applicantEmployerNearestLandmark;
   @org.kie.api.definition.type.Label(value = "Office Telephone Number")
   private java.lang.Long applicantOfficeTelephoneNo;
   @org.kie.api.definition.type.Label(value = "Designation")
   private java.lang.String applicantDesignation;
   @org.kie.api.definition.type.Label(value = "Department")
   private java.lang.String applicantDepartment;
   @org.kie.api.definition.type.Label(value = "Employee No")
   private java.lang.String applicantEmployeeNo;
   @org.kie.api.definition.type.Label(value = "Employed Since")
   private float applicantEmployedSince;
   @org.kie.api.definition.type.Label(value = "Length Of Service")
   private java.lang.Float applicantLengthOfService;

   public ApplicantEmployerDetails()
   {
   }

   public java.lang.String getApplicantEmployerType()
   {
      return this.applicantEmployerType;
   }

   public void setApplicantEmployerType(java.lang.String applicantEmployerType)
   {
      this.applicantEmployerType = applicantEmployerType;
   }

   public java.lang.String getApplicantEmployerName()
   {
      return this.applicantEmployerName;
   }

   public void setApplicantEmployerName(java.lang.String applicantEmployerName)
   {
      this.applicantEmployerName = applicantEmployerName;
   }

   public java.lang.String getApplicantEmployerNameOthers()
   {
      return this.applicantEmployerNameOthers;
   }

   public void setApplicantEmployerNameOthers(
         java.lang.String applicantEmployerNameOthers)
   {
      this.applicantEmployerNameOthers = applicantEmployerNameOthers;
   }

   public java.lang.String getApplicantEmployerAddress()
   {
      return this.applicantEmployerAddress;
   }

   public void setApplicantEmployerAddress(
         java.lang.String applicantEmployerAddress)
   {
      this.applicantEmployerAddress = applicantEmployerAddress;
   }

   public java.lang.String getApplicantEmployerNearestLandmark()
   {
      return this.applicantEmployerNearestLandmark;
   }

   public void setApplicantEmployerNearestLandmark(
         java.lang.String applicantEmployerNearestLandmark)
   {
      this.applicantEmployerNearestLandmark = applicantEmployerNearestLandmark;
   }

   public java.lang.Long getApplicantOfficeTelephoneNo()
   {
      return this.applicantOfficeTelephoneNo;
   }

   public void setApplicantOfficeTelephoneNo(
         java.lang.Long applicantOfficeTelephoneNo)
   {
      this.applicantOfficeTelephoneNo = applicantOfficeTelephoneNo;
   }

   public java.lang.String getApplicantDesignation()
   {
      return this.applicantDesignation;
   }

   public void setApplicantDesignation(java.lang.String applicantDesignation)
   {
      this.applicantDesignation = applicantDesignation;
   }

   public java.lang.String getApplicantDepartment()
   {
      return this.applicantDepartment;
   }

   public void setApplicantDepartment(java.lang.String applicantDepartment)
   {
      this.applicantDepartment = applicantDepartment;
   }

   public java.lang.String getApplicantEmployeeNo()
   {
      return this.applicantEmployeeNo;
   }

   public void setApplicantEmployeeNo(java.lang.String applicantEmployeeNo)
   {
      this.applicantEmployeeNo = applicantEmployeeNo;
   }

   public float getApplicantEmployedSince()
   {
      return this.applicantEmployedSince;
   }

   public void setApplicantEmployedSince(float applicantEmployedSince)
   {
      this.applicantEmployedSince = applicantEmployedSince;
   }

   public java.lang.Float getApplicantLengthOfService()
   {
      return this.applicantLengthOfService;
   }

   public void setApplicantLengthOfService(
         java.lang.Float applicantLengthOfService)
   {
      this.applicantLengthOfService = applicantLengthOfService;
   }

   public ApplicantEmployerDetails(java.lang.String applicantEmployerType,
         java.lang.String applicantEmployerName,
         java.lang.String applicantEmployerNameOthers,
         java.lang.String applicantEmployerAddress,
         java.lang.String applicantEmployerNearestLandmark,
         java.lang.Long applicantOfficeTelephoneNo,
         java.lang.String applicantDesignation,
         java.lang.String applicantDepartment,
         java.lang.String applicantEmployeeNo, float applicantEmployedSince,
         java.lang.Float applicantLengthOfService)
   {
      this.applicantEmployerType = applicantEmployerType;
      this.applicantEmployerName = applicantEmployerName;
      this.applicantEmployerNameOthers = applicantEmployerNameOthers;
      this.applicantEmployerAddress = applicantEmployerAddress;
      this.applicantEmployerNearestLandmark = applicantEmployerNearestLandmark;
      this.applicantOfficeTelephoneNo = applicantOfficeTelephoneNo;
      this.applicantDesignation = applicantDesignation;
      this.applicantDepartment = applicantDepartment;
      this.applicantEmployeeNo = applicantEmployeeNo;
      this.applicantEmployedSince = applicantEmployedSince;
      this.applicantLengthOfService = applicantLengthOfService;
   }

}