package page.loanoriginationsystem;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ApplicantEmployerDetails implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ApplicantEmployerDetails() {
    }

}