package page.loanoriginationsystem;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BankUsageDetails implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Source Channels")
   private java.lang.Short bakSourceChannels;
   @org.kie.api.definition.type.Label(value = "Source Channel Area")
   private java.lang.String bankSourceChannelArea;
   @org.kie.api.definition.type.Label(value = "Sourcing Staff ID")
   private java.lang.String bankSourcingStaffID;
   @org.kie.api.definition.type.Label(value = "Sourcing Staff Name")
   private java.lang.String bankSourcingStaffName;
   @org.kie.api.definition.type.Label(value = "Branch/Sales Comments")
   private java.lang.String bankSalesComments;
   @org.kie.api.definition.type.Label(value = "Other Comments")
   private java.lang.String bankOtherComments;

   public BankUsageDetails()
   {
   }

   public java.lang.Short getBakSourceChannels()
   {
      return this.bakSourceChannels;
   }

   public void setBakSourceChannels(java.lang.Short bakSourceChannels)
   {
      this.bakSourceChannels = bakSourceChannels;
   }

   public java.lang.String getBankSourceChannelArea()
   {
      return this.bankSourceChannelArea;
   }

   public void setBankSourceChannelArea(java.lang.String bankSourceChannelArea)
   {
      this.bankSourceChannelArea = bankSourceChannelArea;
   }

   public java.lang.String getBankSourcingStaffID()
   {
      return this.bankSourcingStaffID;
   }

   public void setBankSourcingStaffID(java.lang.String bankSourcingStaffID)
   {
      this.bankSourcingStaffID = bankSourcingStaffID;
   }

   public java.lang.String getBankSourcingStaffName()
   {
      return this.bankSourcingStaffName;
   }

   public void setBankSourcingStaffName(java.lang.String bankSourcingStaffName)
   {
      this.bankSourcingStaffName = bankSourcingStaffName;
   }

   public java.lang.String getBankSalesComments()
   {
      return this.bankSalesComments;
   }

   public void setBankSalesComments(java.lang.String bankSalesComments)
   {
      this.bankSalesComments = bankSalesComments;
   }

   public java.lang.String getBankOtherComments()
   {
      return this.bankOtherComments;
   }

   public void setBankOtherComments(java.lang.String bankOtherComments)
   {
      this.bankOtherComments = bankOtherComments;
   }

   public BankUsageDetails(java.lang.Short bakSourceChannels,
         java.lang.String bankSourceChannelArea,
         java.lang.String bankSourcingStaffID,
         java.lang.String bankSourcingStaffName,
         java.lang.String bankSalesComments,
         java.lang.String bankOtherComments)
   {
      this.bakSourceChannels = bakSourceChannels;
      this.bankSourceChannelArea = bankSourceChannelArea;
      this.bankSourcingStaffID = bankSourcingStaffID;
      this.bankSourcingStaffName = bankSourcingStaffName;
      this.bankSalesComments = bankSalesComments;
      this.bankOtherComments = bankOtherComments;
   }

}