package com.ps.los;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomerDetails implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Customer Number")
   @org.kie.api.definition.type.Position(1)
   private java.lang.Long customerNumber;
   @org.kie.api.definition.type.Label("Customer Name")
   @org.kie.api.definition.type.Position(2)
   private java.lang.String customerName;
   @org.kie.api.definition.type.Label("Passport Number")
   @org.kie.api.definition.type.Position(3)
   private java.lang.String passportNumber;
   @org.kie.api.definition.type.Label(" National ID Number")
   @org.kie.api.definition.type.Position(4)
   private java.lang.String nationalIDNumber;
   @org.kie.api.definition.type.Label("Nationality")
   @org.kie.api.definition.type.Position(5)
   private java.lang.String nationality;
   @org.kie.api.definition.type.Label("Mobile Number")
   @org.kie.api.definition.type.Position(6)
   private java.lang.String mobileNumber;
   @org.kie.api.definition.type.Label("Email Address")
   @org.kie.api.definition.type.Position(7)
   private java.lang.String emailAddress;
   @org.kie.api.definition.type.Label("Monthly Salary")
   @org.kie.api.definition.type.Position(8)
   private java.lang.Double monthlySalary;
   @org.kie.api.definition.type.Label("Date of Birth")
   @org.kie.api.definition.type.Position(9)
   private java.util.Date dateOfBirth;
   @org.kie.api.definition.type.Label("Mother Maiden Name")
   @org.kie.api.definition.type.Position(10)
   private java.lang.String motherMaidenName;
   @org.kie.api.definition.type.Label("Gender")
   @org.kie.api.definition.type.Position(11)
   private java.lang.String gender;
   @org.kie.api.definition.type.Label("Residence Address")
   @org.kie.api.definition.type.Position(12)
   private java.lang.String residenceAddress;
   @org.kie.api.definition.type.Label("Residence Telephone No")
   @org.kie.api.definition.type.Position(13)
   private java.lang.String residenceTelephoneNo;
   @org.kie.api.definition.type.Label("Home Country Address")
   @org.kie.api.definition.type.Position(14)
   private java.lang.String homeCountryAddress;
   @org.kie.api.definition.type.Label("Home Country Telephone No")
   @org.kie.api.definition.type.Position(15)
   private java.lang.String homeCountryTelephoneNo;
   @org.kie.api.definition.type.Label("Central Bank Blacklist Check")
   @org.kie.api.definition.type.Position(16)
   private java.lang.String centralBankBlacklistCheck;
   @org.kie.api.definition.type.Label("Internal Blacklist Check")
   @org.kie.api.definition.type.Position(17)
   private java.lang.String internalBlacklistCheck;

   public CustomerDetails()
   {
   }

   public java.lang.Long getCustomerNumber()
   {
      return this.customerNumber;
   }

   public void setCustomerNumber(java.lang.Long customerNumber)
   {
      this.customerNumber = customerNumber;
   }

   public java.lang.String getCustomerName()
   {
      return this.customerName;
   }

   public void setCustomerName(java.lang.String customerName)
   {
      this.customerName = customerName;
   }

   public java.lang.String getPassportNumber()
   {
      return this.passportNumber;
   }

   public void setPassportNumber(java.lang.String passportNumber)
   {
      this.passportNumber = passportNumber;
   }

   public java.lang.String getNationalIDNumber()
   {
      return this.nationalIDNumber;
   }

   public void setNationalIDNumber(java.lang.String nationalIDNumber)
   {
      this.nationalIDNumber = nationalIDNumber;
   }

   public java.lang.String getNationality()
   {
      return this.nationality;
   }

   public void setNationality(java.lang.String nationality)
   {
      this.nationality = nationality;
   }

   public java.lang.String getMobileNumber()
   {
      return this.mobileNumber;
   }

   public void setMobileNumber(java.lang.String mobileNumber)
   {
      this.mobileNumber = mobileNumber;
   }

   public java.lang.String getEmailAddress()
   {
      return this.emailAddress;
   }

   public void setEmailAddress(java.lang.String emailAddress)
   {
      this.emailAddress = emailAddress;
   }

   public java.lang.Double getMonthlySalary()
   {
      return this.monthlySalary;
   }

   public void setMonthlySalary(java.lang.Double monthlySalary)
   {
      this.monthlySalary = monthlySalary;
   }

   public java.util.Date getDateOfBirth()
   {
      return this.dateOfBirth;
   }

   public void setDateOfBirth(java.util.Date dateOfBirth)
   {
      this.dateOfBirth = dateOfBirth;
   }

   public java.lang.String getMotherMaidenName()
   {
      return this.motherMaidenName;
   }

   public void setMotherMaidenName(java.lang.String motherMaidenName)
   {
      this.motherMaidenName = motherMaidenName;
   }

   public java.lang.String getGender()
   {
      return this.gender;
   }

   public void setGender(java.lang.String gender)
   {
      this.gender = gender;
   }

   public java.lang.String getResidenceAddress()
   {
      return this.residenceAddress;
   }

   public void setResidenceAddress(java.lang.String residenceAddress)
   {
      this.residenceAddress = residenceAddress;
   }

   public java.lang.String getResidenceTelephoneNo()
   {
      return this.residenceTelephoneNo;
   }

   public void setResidenceTelephoneNo(java.lang.String residenceTelephoneNo)
   {
      this.residenceTelephoneNo = residenceTelephoneNo;
   }

   public java.lang.String getHomeCountryAddress()
   {
      return this.homeCountryAddress;
   }

   public void setHomeCountryAddress(java.lang.String homeCountryAddress)
   {
      this.homeCountryAddress = homeCountryAddress;
   }

   public java.lang.String getHomeCountryTelephoneNo()
   {
      return this.homeCountryTelephoneNo;
   }

   public void setHomeCountryTelephoneNo(
         java.lang.String homeCountryTelephoneNo)
   {
      this.homeCountryTelephoneNo = homeCountryTelephoneNo;
   }

   public java.lang.String getCentralBankBlacklistCheck()
   {
      return this.centralBankBlacklistCheck;
   }

   public void setCentralBankBlacklistCheck(
         java.lang.String centralBankBlacklistCheck)
   {
      this.centralBankBlacklistCheck = centralBankBlacklistCheck;
   }

   public java.lang.String getInternalBlacklistCheck()
   {
      return this.internalBlacklistCheck;
   }

   public void setInternalBlacklistCheck(
         java.lang.String internalBlacklistCheck)
   {
      this.internalBlacklistCheck = internalBlacklistCheck;
   }

   public CustomerDetails(java.lang.Long customerNumber,
         java.lang.String customerName, java.lang.String passportNumber,
         java.lang.String nationalIDNumber, java.lang.String nationality,
         java.lang.String mobileNumber, java.lang.String emailAddress,
         java.lang.Double monthlySalary, java.util.Date dateOfBirth,
         java.lang.String motherMaidenName, java.lang.String gender,
         java.lang.String residenceAddress,
         java.lang.String residenceTelephoneNo,
         java.lang.String homeCountryAddress,
         java.lang.String homeCountryTelephoneNo,
         java.lang.String centralBankBlacklistCheck,
         java.lang.String internalBlacklistCheck)
   {
      this.customerNumber = customerNumber;
      this.customerName = customerName;
      this.passportNumber = passportNumber;
      this.nationalIDNumber = nationalIDNumber;
      this.nationality = nationality;
      this.mobileNumber = mobileNumber;
      this.emailAddress = emailAddress;
      this.monthlySalary = monthlySalary;
      this.dateOfBirth = dateOfBirth;
      this.motherMaidenName = motherMaidenName;
      this.gender = gender;
      this.residenceAddress = residenceAddress;
      this.residenceTelephoneNo = residenceTelephoneNo;
      this.homeCountryAddress = homeCountryAddress;
      this.homeCountryTelephoneNo = homeCountryTelephoneNo;
      this.centralBankBlacklistCheck = centralBankBlacklistCheck;
      this.internalBlacklistCheck = internalBlacklistCheck;
   }

}