package com.ps.los;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LoanDetails implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Customer Type")
   private java.lang.String customerType;

   @org.kie.api.definition.type.Label("Financing Insurance")
   private java.lang.String financingInsurance;

   @org.kie.api.definition.type.Label("Insurance Amount")
   private java.lang.Double insuranceAmount;

   @org.kie.api.definition.type.Label("Financing Registration")
   private java.lang.String financingRegistration;

   @org.kie.api.definition.type.Label("Registration")
   private java.lang.Integer registration;

   @org.kie.api.definition.type.Label("Proposed Finance Amount")
   private java.lang.Double proposedFinanceAmount;

   @org.kie.api.definition.type.Label("Down Payment Amount")
   private java.lang.Double downPaymentAmount;

   @org.kie.api.definition.type.Label("Finance Amount")
   private java.lang.Double financeAmount;

   @org.kie.api.definition.type.Label("Profit / Interest Rate type")
   private String interestRatetype;

   @org.kie.api.definition.type.Label("Profit / Interest Rate key")
   private java.lang.Float interestRatekey;

   @org.kie.api.definition.type.Label("Profit / Interest Rate")
   private java.lang.Double interestRate;

   @org.kie.api.definition.type.Label("Profit / Interest Rate Spread")
   private java.lang.Double interestRateSpread;

   @org.kie.api.definition.type.Label("Tenor (Months)")
   private java.lang.Integer tenorMonths;

   @org.kie.api.definition.type.Label("Tenor (years)")
   private java.lang.Integer tenorYears;

   @org.kie.api.definition.type.Label("First Installment Date")
   private java.util.Date firstInstallmentDate;

   @org.kie.api.definition.type.Label("Last Installment Date")
   private java.util.Date lastInstallmentDate;

   public LoanDetails()
   {
   }

   public java.lang.String getCustomerType()
   {
      return this.customerType;
   }

   public void setCustomerType(java.lang.String customerType)
   {
      this.customerType = customerType;
   }

   public java.lang.String getFinancingInsurance()
   {
      return this.financingInsurance;
   }

   public void setFinancingInsurance(java.lang.String financingInsurance)
   {
      this.financingInsurance = financingInsurance;
   }

   public java.lang.Double getInsuranceAmount()
   {
      return this.insuranceAmount;
   }

   public void setInsuranceAmount(java.lang.Double insuranceAmount)
   {
      this.insuranceAmount = insuranceAmount;
   }

   public java.lang.String getFinancingRegistration()
   {
      return this.financingRegistration;
   }

   public void setFinancingRegistration(java.lang.String financingRegistration)
   {
      this.financingRegistration = financingRegistration;
   }

   public java.lang.Integer getRegistration()
   {
      return this.registration;
   }

   public void setRegistration(java.lang.Integer registration)
   {
      this.registration = registration;
   }

   public java.lang.Double getProposedFinanceAmount()
   {
      return this.proposedFinanceAmount;
   }

   public void setProposedFinanceAmount(java.lang.Double proposedFinanceAmount)
   {
      this.proposedFinanceAmount = proposedFinanceAmount;
   }

   public java.lang.Double getDownPaymentAmount()
   {
      return this.downPaymentAmount;
   }

   public void setDownPaymentAmount(java.lang.Double downPaymentAmount)
   {
      this.downPaymentAmount = downPaymentAmount;
   }

   public java.lang.Double getFinanceAmount()
   {
      return this.financeAmount;
   }

   public void setFinanceAmount(java.lang.Double financeAmount)
   {
      this.financeAmount = financeAmount;
   }

   public java.lang.Float getInterestRatekey()
   {
      return this.interestRatekey;
   }

   public void setInterestRatekey(java.lang.Float interestRatekey)
   {
      this.interestRatekey = interestRatekey;
   }

   public java.lang.Double getInterestRate()
   {
      return this.interestRate;
   }

   public void setInterestRate(java.lang.Double interestRate)
   {
      this.interestRate = interestRate;
   }

   public java.lang.Double getInterestRateSpread()
   {
      return this.interestRateSpread;
   }

   public void setInterestRateSpread(java.lang.Double interestRateSpread)
   {
      this.interestRateSpread = interestRateSpread;
   }

   public java.lang.Integer getTenorMonths()
   {
      return this.tenorMonths;
   }

   public void setTenorMonths(java.lang.Integer tenorMonths)
   {
      this.tenorMonths = tenorMonths;
   }

   public java.lang.Integer getTenorYears()
   {
      return this.tenorYears;
   }

   public void setTenorYears(java.lang.Integer tenorYears)
   {
      this.tenorYears = tenorYears;
   }

   public java.util.Date getFirstInstallmentDate()
   {
      return this.firstInstallmentDate;
   }

   public void setFirstInstallmentDate(java.util.Date firstInstallmentDate)
   {
      this.firstInstallmentDate = firstInstallmentDate;
   }

   public java.util.Date getLastInstallmentDate()
   {
      return this.lastInstallmentDate;
   }

   public void setLastInstallmentDate(java.util.Date lastInstallmentDate)
   {
      this.lastInstallmentDate = lastInstallmentDate;
   }

   public java.lang.String getInterestRatetype()
   {
      return this.interestRatetype;
   }

   public void setInterestRatetype(java.lang.String interestRatetype)
   {
      this.interestRatetype = interestRatetype;
   }

   public LoanDetails(java.lang.String customerType,
         java.lang.String financingInsurance, java.lang.Double insuranceAmount,
         java.lang.String financingRegistration, java.lang.Integer registration,
         java.lang.Double proposedFinanceAmount,
         java.lang.Double downPaymentAmount, java.lang.Double financeAmount,
         java.lang.String interestRatetype, java.lang.Float interestRatekey,
         java.lang.Double interestRate, java.lang.Double interestRateSpread,
         java.lang.Integer tenorMonths, java.lang.Integer tenorYears,
         java.util.Date firstInstallmentDate, java.util.Date lastInstallmentDate)
   {
      this.customerType = customerType;
      this.financingInsurance = financingInsurance;
      this.insuranceAmount = insuranceAmount;
      this.financingRegistration = financingRegistration;
      this.registration = registration;
      this.proposedFinanceAmount = proposedFinanceAmount;
      this.downPaymentAmount = downPaymentAmount;
      this.financeAmount = financeAmount;
      this.interestRatetype = interestRatetype;
      this.interestRatekey = interestRatekey;
      this.interestRate = interestRate;
      this.interestRateSpread = interestRateSpread;
      this.tenorMonths = tenorMonths;
      this.tenorYears = tenorYears;
      this.firstInstallmentDate = firstInstallmentDate;
      this.lastInstallmentDate = lastInstallmentDate;
   }

}