package page.loanoriginationsystem;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LoanJointApplicantDetails implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Customer No")
   private java.math.BigInteger jointApplicantCustomerNo;
   @org.kie.api.definition.type.Label(value = "Customer Name")
   private java.lang.String jointApplicantName;
   @org.kie.api.definition.type.Label(value = "Date of Birth")
   private java.util.Date jointApplicantDOB;
   @org.kie.api.definition.type.Label(value = "Mobile Number")
   private java.lang.Long jointApplicantMobileNo;
   @org.kie.api.definition.type.Label(value = "Email Address")
   private java.lang.String jointApplicantEmailAddress;
   @org.kie.api.definition.type.Label(value = "Residence Telephone No")
   private java.lang.Long jointApplicantResidenceTelephoneNo;
   @org.kie.api.definition.type.Label(value = "Monthly Salary/Income")
   private java.lang.Double jointApplicantMonthlyIncome;
   @org.kie.api.definition.type.Label(value = "Mother Maiden Name")
   private java.lang.String jointApplicantMotherMaidenName;
   @org.kie.api.definition.type.Label(value = "Gender")
   private java.lang.Short jointApplicantGender;
   @org.kie.api.definition.type.Label(value = "Passport No")
   private java.lang.String jointApplicantPassportNo;
   @org.kie.api.definition.type.Label(value = "National ID No")
   private java.lang.String jointApplicantNationalIDNo;
   @org.kie.api.definition.type.Label(value = "Occupation")
   private java.lang.String jointApplicantOccupation;
   @org.kie.api.definition.type.Label(value = "Company Name")
   private java.lang.String jointApplicantCompanyName;
   @org.kie.api.definition.type.Label(value = "Office Telephone Number")
   private java.lang.Long jointApplicantOfficeTelephoneNo;
   @org.kie.api.definition.type.Label(value = "Designation")
   private java.lang.String jointApplicantDesignation;
   @org.kie.api.definition.type.Label(value = "Employed/Years in Business Since")
   private java.lang.Integer jointApplicantWorkExp;
   @org.kie.api.definition.type.Label(value = "Relationship with Applicant 1")
   private java.lang.String jointApplicantRelationWithApplicant;

   public LoanJointApplicantDetails()
   {
   }

   public java.math.BigInteger getJointApplicantCustomerNo()
   {
      return this.jointApplicantCustomerNo;
   }

   public void setJointApplicantCustomerNo(
         java.math.BigInteger jointApplicantCustomerNo)
   {
      this.jointApplicantCustomerNo = jointApplicantCustomerNo;
   }

   public java.lang.String getJointApplicantName()
   {
      return this.jointApplicantName;
   }

   public void setJointApplicantName(java.lang.String jointApplicantName)
   {
      this.jointApplicantName = jointApplicantName;
   }

   public java.util.Date getJointApplicantDOB()
   {
      return this.jointApplicantDOB;
   }

   public void setJointApplicantDOB(java.util.Date jointApplicantDOB)
   {
      this.jointApplicantDOB = jointApplicantDOB;
   }

   public java.lang.Long getJointApplicantMobileNo()
   {
      return this.jointApplicantMobileNo;
   }

   public void setJointApplicantMobileNo(java.lang.Long jointApplicantMobileNo)
   {
      this.jointApplicantMobileNo = jointApplicantMobileNo;
   }

   public java.lang.String getJointApplicantEmailAddress()
   {
      return this.jointApplicantEmailAddress;
   }

   public void setJointApplicantEmailAddress(
         java.lang.String jointApplicantEmailAddress)
   {
      this.jointApplicantEmailAddress = jointApplicantEmailAddress;
   }

   public java.lang.Long getJointApplicantResidenceTelephoneNo()
   {
      return this.jointApplicantResidenceTelephoneNo;
   }

   public void setJointApplicantResidenceTelephoneNo(
         java.lang.Long jointApplicantResidenceTelephoneNo)
   {
      this.jointApplicantResidenceTelephoneNo = jointApplicantResidenceTelephoneNo;
   }

   public java.lang.Double getJointApplicantMonthlyIncome()
   {
      return this.jointApplicantMonthlyIncome;
   }

   public void setJointApplicantMonthlyIncome(
         java.lang.Double jointApplicantMonthlyIncome)
   {
      this.jointApplicantMonthlyIncome = jointApplicantMonthlyIncome;
   }

   public java.lang.String getJointApplicantMotherMaidenName()
   {
      return this.jointApplicantMotherMaidenName;
   }

   public void setJointApplicantMotherMaidenName(
         java.lang.String jointApplicantMotherMaidenName)
   {
      this.jointApplicantMotherMaidenName = jointApplicantMotherMaidenName;
   }

   public java.lang.Short getJointApplicantGender()
   {
      return this.jointApplicantGender;
   }

   public void setJointApplicantGender(java.lang.Short jointApplicantGender)
   {
      this.jointApplicantGender = jointApplicantGender;
   }

   public java.lang.String getJointApplicantPassportNo()
   {
      return this.jointApplicantPassportNo;
   }

   public void setJointApplicantPassportNo(
         java.lang.String jointApplicantPassportNo)
   {
      this.jointApplicantPassportNo = jointApplicantPassportNo;
   }

   public java.lang.String getJointApplicantNationalIDNo()
   {
      return this.jointApplicantNationalIDNo;
   }

   public void setJointApplicantNationalIDNo(
         java.lang.String jointApplicantNationalIDNo)
   {
      this.jointApplicantNationalIDNo = jointApplicantNationalIDNo;
   }

   public java.lang.String getJointApplicantOccupation()
   {
      return this.jointApplicantOccupation;
   }

   public void setJointApplicantOccupation(
         java.lang.String jointApplicantOccupation)
   {
      this.jointApplicantOccupation = jointApplicantOccupation;
   }

   public java.lang.String getJointApplicantCompanyName()
   {
      return this.jointApplicantCompanyName;
   }

   public void setJointApplicantCompanyName(
         java.lang.String jointApplicantCompanyName)
   {
      this.jointApplicantCompanyName = jointApplicantCompanyName;
   }

   public java.lang.Long getJointApplicantOfficeTelephoneNo()
   {
      return this.jointApplicantOfficeTelephoneNo;
   }

   public void setJointApplicantOfficeTelephoneNo(
         java.lang.Long jointApplicantOfficeTelephoneNo)
   {
      this.jointApplicantOfficeTelephoneNo = jointApplicantOfficeTelephoneNo;
   }

   public java.lang.String getJointApplicantDesignation()
   {
      return this.jointApplicantDesignation;
   }

   public void setJointApplicantDesignation(
         java.lang.String jointApplicantDesignation)
   {
      this.jointApplicantDesignation = jointApplicantDesignation;
   }

   public java.lang.Integer getJointApplicantWorkExp()
   {
      return this.jointApplicantWorkExp;
   }

   public void setJointApplicantWorkExp(java.lang.Integer jointApplicantWorkExp)
   {
      this.jointApplicantWorkExp = jointApplicantWorkExp;
   }

   public java.lang.String getJointApplicantRelationWithApplicant()
   {
      return this.jointApplicantRelationWithApplicant;
   }

   public void setJointApplicantRelationWithApplicant(
         java.lang.String jointApplicantRelationWithApplicant)
   {
      this.jointApplicantRelationWithApplicant = jointApplicantRelationWithApplicant;
   }

   public LoanJointApplicantDetails(
         java.math.BigInteger jointApplicantCustomerNo,
         java.lang.String jointApplicantName,
         java.util.Date jointApplicantDOB,
         java.lang.Long jointApplicantMobileNo,
         java.lang.String jointApplicantEmailAddress,
         java.lang.Long jointApplicantResidenceTelephoneNo,
         java.lang.Double jointApplicantMonthlyIncome,
         java.lang.String jointApplicantMotherMaidenName,
         java.lang.Short jointApplicantGender,
         java.lang.String jointApplicantPassportNo,
         java.lang.String jointApplicantNationalIDNo,
         java.lang.String jointApplicantOccupation,
         java.lang.String jointApplicantCompanyName,
         java.lang.Long jointApplicantOfficeTelephoneNo,
         java.lang.String jointApplicantDesignation,
         java.lang.Integer jointApplicantWorkExp,
         java.lang.String jointApplicantRelationWithApplicant)
   {
      this.jointApplicantCustomerNo = jointApplicantCustomerNo;
      this.jointApplicantName = jointApplicantName;
      this.jointApplicantDOB = jointApplicantDOB;
      this.jointApplicantMobileNo = jointApplicantMobileNo;
      this.jointApplicantEmailAddress = jointApplicantEmailAddress;
      this.jointApplicantResidenceTelephoneNo = jointApplicantResidenceTelephoneNo;
      this.jointApplicantMonthlyIncome = jointApplicantMonthlyIncome;
      this.jointApplicantMotherMaidenName = jointApplicantMotherMaidenName;
      this.jointApplicantGender = jointApplicantGender;
      this.jointApplicantPassportNo = jointApplicantPassportNo;
      this.jointApplicantNationalIDNo = jointApplicantNationalIDNo;
      this.jointApplicantOccupation = jointApplicantOccupation;
      this.jointApplicantCompanyName = jointApplicantCompanyName;
      this.jointApplicantOfficeTelephoneNo = jointApplicantOfficeTelephoneNo;
      this.jointApplicantDesignation = jointApplicantDesignation;
      this.jointApplicantWorkExp = jointApplicantWorkExp;
      this.jointApplicantRelationWithApplicant = jointApplicantRelationWithApplicant;
   }

}