package page.loanoriginationsystem;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class VehicleCarDetails implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   public VehicleCarDetails()
   {
   }

}