package com.ps.los;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AddBlacklistCheck implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Add Blacklist Check")
   private java.util.List<com.ps.los.BlacklistCheck> addBlacklistCheck;

   @org.kie.api.definition.type.Label(value = "Amount")
   private java.lang.Double amount;

   @org.kie.api.definition.type.Label(value = "Blacklist Type")
   private java.lang.String blacklistType;

   public AddBlacklistCheck()
   {
   }

   public java.util.List<com.ps.los.BlacklistCheck> getAddBlacklistCheck()
   {
      return this.addBlacklistCheck;
   }

   public void setAddBlacklistCheck(
         java.util.List<com.ps.los.BlacklistCheck> addBlacklistCheck)
   {
      this.addBlacklistCheck = addBlacklistCheck;
   }

   public java.lang.Double getAmount()
   {
      return this.amount;
   }

   public void setAmount(java.lang.Double amount)
   {
      this.amount = amount;
   }

   public java.lang.String getBlacklistType()
   {
      return this.blacklistType;
   }

   public void setBlacklistType(java.lang.String blacklistType)
   {
      this.blacklistType = blacklistType;
   }

   public AddBlacklistCheck(
         java.util.List<com.ps.los.BlacklistCheck> addBlacklistCheck,
         java.lang.Double amount, java.lang.String blacklistType)
   {
      this.addBlacklistCheck = addBlacklistCheck;
      this.amount = amount;
      this.blacklistType = blacklistType;
   }

}