package com.ps.los;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BankUsageDetails implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Source Channels")
   @org.kie.api.definition.type.Position(1)
   private String bankSourceChannels;
   @org.kie.api.definition.type.Label("Source Channel Area")
   @org.kie.api.definition.type.Position(4)
   private java.lang.String bankSourceChannelArea;
   @org.kie.api.definition.type.Label("Sourcing Staff ID")
   @org.kie.api.definition.type.Position(5)
   private java.lang.String bankSourcingStaffID;
   @org.kie.api.definition.type.Label("Sourcing Staff Name")
   @org.kie.api.definition.type.Position(6)
   private java.lang.String bankSourcingStaffName;
   @org.kie.api.definition.type.Label("Branch/Sales Comments")
   @org.kie.api.definition.type.Position(3)
   private java.lang.String bankSalesComments;
   @org.kie.api.definition.type.Label("Other Comments")
   @org.kie.api.definition.type.Position(2)
   private java.lang.String bankOtherComments;

   public BankUsageDetails()
   {
   }

   public java.lang.String getBankSourceChannelArea()
   {
      return this.bankSourceChannelArea;
   }

   public void setBankSourceChannelArea(java.lang.String bankSourceChannelArea)
   {
      this.bankSourceChannelArea = bankSourceChannelArea;
   }

   public java.lang.String getBankSourcingStaffID()
   {
      return this.bankSourcingStaffID;
   }

   public void setBankSourcingStaffID(java.lang.String bankSourcingStaffID)
   {
      this.bankSourcingStaffID = bankSourcingStaffID;
   }

   public java.lang.String getBankSourcingStaffName()
   {
      return this.bankSourcingStaffName;
   }

   public void setBankSourcingStaffName(java.lang.String bankSourcingStaffName)
   {
      this.bankSourcingStaffName = bankSourcingStaffName;
   }

   public java.lang.String getBankSalesComments()
   {
      return this.bankSalesComments;
   }

   public void setBankSalesComments(java.lang.String bankSalesComments)
   {
      this.bankSalesComments = bankSalesComments;
   }

   public java.lang.String getBankOtherComments()
   {
      return this.bankOtherComments;
   }

   public void setBankOtherComments(java.lang.String bankOtherComments)
   {
      this.bankOtherComments = bankOtherComments;
   }

   public java.lang.String getBankSourceChannels()
   {
      return this.bankSourceChannels;
   }

   public void setBankSourceChannels(java.lang.String bankSourceChannels)
   {
      this.bankSourceChannels = bankSourceChannels;
   }

   public BankUsageDetails(java.lang.String bankSourceChannels,
         java.lang.String bankSourceChannelArea,
         java.lang.String bankSourcingStaffID,
         java.lang.String bankSourcingStaffName,
         java.lang.String bankSalesComments, java.lang.String bankOtherComments)
   {
      this.bankSourceChannels = bankSourceChannels;
      this.bankSourceChannelArea = bankSourceChannelArea;
      this.bankSourcingStaffID = bankSourcingStaffID;
      this.bankSourcingStaffName = bankSourcingStaffName;
      this.bankSalesComments = bankSalesComments;
      this.bankOtherComments = bankOtherComments;
   }

}