package com.ps.los;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BlacklistCheck implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public BlacklistCheck() {
    }

}