package com.ps.los;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CreditScoringData implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Gender Credit Score")
   private java.lang.Integer gender_creditScore;
   @org.kie.api.definition.type.Label(value = "Age Credit Score")
   private java.lang.Integer age_creditScore;
   @org.kie.api.definition.type.Label(value = "Salary Credit Score")
   private java.lang.Integer salary_creditScore;

   public CreditScoringData()
   {
   }

   public java.lang.Integer getGender_creditScore()
   {
      return this.gender_creditScore;
   }

   public void setGender_creditScore(java.lang.Integer gender_creditScore)
   {
      this.gender_creditScore = gender_creditScore;
   }

   public java.lang.Integer getAge_creditScore()
   {
      return this.age_creditScore;
   }

   public void setAge_creditScore(java.lang.Integer age_creditScore)
   {
      this.age_creditScore = age_creditScore;
   }

   public java.lang.Integer getSalary_creditScore()
   {
      return this.salary_creditScore;
   }

   public void setSalary_creditScore(java.lang.Integer salary_creditScore)
   {
      this.salary_creditScore = salary_creditScore;
   }

   public CreditScoringData(java.lang.Integer gender_creditScore,
         java.lang.Integer age_creditScore,
         java.lang.Integer salary_creditScore)
   {
      this.gender_creditScore = gender_creditScore;
      this.age_creditScore = age_creditScore;
      this.salary_creditScore = salary_creditScore;
   }

}