package com.ps.los;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DeviationBlacklistCheck implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Central Bank Blackliist Check")
   private java.lang.String centralBankBlackliistCheck;
   @org.kie.api.definition.type.Label(value = "Amount")
   private java.lang.Double amount;
   @org.kie.api.definition.type.Label(value = "\t Blacklist Report")
   private org.jbpm.document.Document blackListReportDocument;

   public DeviationBlacklistCheck()
   {
   }

   public java.lang.String getCentralBankBlackliistCheck()
   {
      return this.centralBankBlackliistCheck;
   }

   public void setCentralBankBlackliistCheck(
         java.lang.String centralBankBlackliistCheck)
   {
      this.centralBankBlackliistCheck = centralBankBlackliistCheck;
   }

   public java.lang.Double getAmount()
   {
      return this.amount;
   }

   public void setAmount(java.lang.Double amount)
   {
      this.amount = amount;
   }

   public org.jbpm.document.Document getBlackListReportDocument()
   {
      return this.blackListReportDocument;
   }

   public void setBlackListReportDocument(
         org.jbpm.document.Document blackListReportDocument)
   {
      this.blackListReportDocument = blackListReportDocument;
   }

   public DeviationBlacklistCheck(java.lang.String centralBankBlackliistCheck,
         java.lang.Double amount, org.jbpm.document.Document blackListReportDocument)
   {
      this.centralBankBlackliistCheck = centralBankBlackliistCheck;
      this.amount = amount;
      this.blackListReportDocument = blackListReportDocument;
   }

}