package com.ps.los;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LoanApplicationDetails implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Incident Date")
   private java.util.Date incidentDate;
   @org.kie.api.definition.type.Label(value = "Incident#")
   private java.lang.String incidentNumber;
   @org.kie.api.definition.type.Label(value = "Applicant Type")
   private java.lang.String applicationType;
   @org.kie.api.definition.type.Label(value = "Applicant Status")
   private java.lang.String applicantStatus;
   @org.kie.api.definition.type.Label(value = "Relationship")
   private java.lang.String appRelationship;

   public LoanApplicationDetails()
   {
   }

   public java.util.Date getIncidentDate()
   {
      return this.incidentDate;
   }

   public void setIncidentDate(java.util.Date incidentDate)
   {
      this.incidentDate = incidentDate;
   }

   public java.lang.String getIncidentNumber()
   {
      return this.incidentNumber;
   }

   public void setIncidentNumber(java.lang.String incidentNumber)
   {
      this.incidentNumber = incidentNumber;
   }

   public java.lang.String getApplicationType()
   {
      return this.applicationType;
   }

   public void setApplicationType(java.lang.String applicationType)
   {
      this.applicationType = applicationType;
   }

   public java.lang.String getApplicantStatus()
   {
      return this.applicantStatus;
   }

   public void setApplicantStatus(java.lang.String applicantStatus)
   {
      this.applicantStatus = applicantStatus;
   }

   public java.lang.String getAppRelationship()
   {
      return this.appRelationship;
   }

   public void setAppRelationship(java.lang.String appRelationship)
   {
      this.appRelationship = appRelationship;
   }

   public LoanApplicationDetails(java.util.Date incidentDate,
         java.lang.String incidentNumber, java.lang.String applicationType,
         java.lang.String applicantStatus, java.lang.String appRelationship)
   {
      this.incidentDate = incidentDate;
      this.incidentNumber = incidentNumber;
      this.applicationType = applicationType;
      this.applicantStatus = applicantStatus;
      this.appRelationship = appRelationship;
   }

}