package com.ps.los;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OutProcessChecking implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private com.ps.los.LoanApplicationDetails loanApplicationDetails;
   private com.ps.los.LoanDetails loanDetails;
   @org.kie.api.definition.type.Label(value = "Loan Approved")
   private java.lang.String loanApproved;
   @org.kie.api.definition.type.Label(value = "Comments")
   private java.lang.String loanApprovalDescription;

   public OutProcessChecking()
   {
   }

   public com.ps.los.LoanApplicationDetails getLoanApplicationDetails()
   {
      return this.loanApplicationDetails;
   }

   public void setLoanApplicationDetails(
         com.ps.los.LoanApplicationDetails loanApplicationDetails)
   {
      this.loanApplicationDetails = loanApplicationDetails;
   }

   public com.ps.los.LoanDetails getLoanDetails()
   {
      return this.loanDetails;
   }

   public void setLoanDetails(com.ps.los.LoanDetails loanDetails)
   {
      this.loanDetails = loanDetails;
   }

   public java.lang.String getLoanApproved()
   {
      return this.loanApproved;
   }

   public void setLoanApproved(java.lang.String loanApproved)
   {
      this.loanApproved = loanApproved;
   }

   public java.lang.String getLoanApprovalDescription()
   {
      return this.loanApprovalDescription;
   }

   public void setLoanApprovalDescription(
         java.lang.String loanApprovalDescription)
   {
      this.loanApprovalDescription = loanApprovalDescription;
   }

   public OutProcessChecking(
         com.ps.los.LoanApplicationDetails loanApplicationDetails,
         com.ps.los.LoanDetails loanDetails, java.lang.String loanApproved,
         java.lang.String loanApprovalDescription)
   {
      this.loanApplicationDetails = loanApplicationDetails;
      this.loanDetails = loanDetails;
      this.loanApproved = loanApproved;
      this.loanApprovalDescription = loanApprovalDescription;
   }

}